# Generated by Django 2.1.2 on 2019-01-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='contribution_total',
            new_name='contribution_total_2018',
        ),
    ]
