# Generated by Django 2.1.2 on 2019-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20190115_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='contribution_total_2020',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
