# Generated by Django 2.1.5 on 2019-01-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_contribution_total_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contribution_total_2018',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contribution_total_2020',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
