from django.db import models
from django.utils import timezone

class BaseModel(models.Model):
    active = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.__str__()

class Committee(BaseModel):
    fec_id = models.CharField(max_length=10, primary_key=True)
    committee_name = models.CharField(max_length=255, blank=True, null=True)
    street_1 = models.CharField(max_length=255, blank=True, null=True)
    street_2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=20, blank=True, null=True)
    zipcode = models.CharField(max_length=10, blank=True, null=True)
    treasurer_last_name = models.CharField(max_length=255, blank=True, null=True)
    treasurer_first_name = models.CharField(max_length=255, blank=True, null=True)
    treasurer_middle_name = models.CharField(max_length=255, blank=True, null=True)
    treasurer_prefix = models.CharField(max_length=255, blank=True, null=True)
    treasurer_suffix = models.CharField(max_length=255, blank=True, null=True)
    committee_type = models.CharField(max_length=1, blank=True, null=True)
    committee_designation = models.CharField(max_length=1, blank=True, null=True)

class Filing(BaseModel):
    filing_id = models.IntegerField(primary_key=True)
    form_type = models.CharField(max_length=20, null=True, blank=True, help_text='the full form type from the filing')
    form = models.CharField(max_length=20, null=True, blank=True, help_text='the base form type (excluding amendment indications)')
    filer_id = models.CharField(max_length=10, null=True, blank=True, help_text='FEC id of the filer')
    committee_name = models.CharField(max_length=255, null=True, blank=True)
    election_state = models.CharField(max_length=10, null=True, blank=True)
    election_district = models.CharField(max_length=10, null=True, blank=True)
    coverage_from_date = models.CharField(max_length=10, null=True, blank=True)
    coverage_through_date = models.CharField(max_length=10, null=True, blank=True)
    date_signed = models.CharField(max_length=10, null=True, blank=True)
    cash_on_hand_close_of_period = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cash_on_hand_beginning_period = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    debts_by_summary = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True,help_text="Current debt owed by the committee")
    period_candidate_contributions=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_candidate_loan_repayments=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_candidate_loans=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_contributions_to_candidates=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_coordinated_expenditures_by_party_committees=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_exempt_legal_accounting_disbursement=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_federal_election_activity_all_federal=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_federal_election_activity_federal_share=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_federal_election_activity_levin_share=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_federal_election_activity_total=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_fundraising=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_fundraising_disbursements=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_independent_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_individual_contribution_total=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_individuals_itemized=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_individuals_unitemized=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_items_on_hand_to_be_liquidated=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_legal_and_accounting=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_levin_funds=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_loans_made=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_made_or_guaranteed_by_candidate=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_net_contributions=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_net_operating_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_offsets_to_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_operating=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_operating_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_disbursements=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_federal_operating_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_federal_receipts=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_loan_repayments=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_loans=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_political_committees=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_political_committees_pacs=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_receipts=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_other_repayments=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_pac_contributions=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_political_party_committees_refunds=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_political_party_contributions=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_received_from_or_guaranteed_by_cand=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_refunds_to_individuals=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_refunds_to_other_committees=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_refunds_to_party_committees=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_shared_operating_expenditures_federal=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_shared_operating_expenditures_nonfederal=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_contributions_from_candidate=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_contributions=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_contributions_refunds=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_disbursements=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_disbursements_period=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_federal_disbursements=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_federal_operating_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_federal_receipts=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_individual_contributions=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_loan_repayments_made=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_loan_repayments_received=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_loans=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_nonfederal_transfers=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_offset_to_operating_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_operating_expenditures=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_receipts=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_total_refunds=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_transfers_from_aff_other_party_cmttees=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_transfers_from_authorized=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_transfers_from_nonfederal_h3=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_transfers_to_affiliated=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    period_transfers_to_other_authorized_committees=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_candidate_contributions = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_candidate_loan_repayments = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_candidate_loans = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_contributions_to_candidates = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_coordinated_expenditures_by_party_committees = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_exempt_legal_accounting_disbursement = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_federal_election_activity_all_federal = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_federal_election_activity_federal_share = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_federal_election_activity_levin_share = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_federal_election_activity_total = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_fundraising = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_fundraising_disbursements = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_independent_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_individual_contribution_total = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_individuals_itemized = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_individuals_unitemized = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_items_on_hand_to_be_liquidated = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_legal_and_accounting = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_levin_funds = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_loans_made = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_made_or_guaranteed_by_candidate = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_net_contributions = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_net_operating_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_offsets_to_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_operating = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_operating_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_disbursements = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_federal_operating_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_federal_receipts = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_loan_repayments = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_loans = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_political_committees = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_political_committees_pacs = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_receipts = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_other_repayments = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_pac_contributions = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_political_party_committees_refunds = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_political_party_contributions = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_received_from_or_guaranteed_by_cand = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_refunds_to_individuals = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_refunds_to_other_committees = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_refunds_to_party_committees = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_shared_operating_expenditures_federal = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_shared_operating_expenditures_nonfederal = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_contributions_from_candidate = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_contributions = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_contributions_refunds = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_disbursements = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_disbursements_period = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_federal_disbursements = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_federal_operating_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_federal_receipts = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_individual_contributions = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_loan_repayments_made = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_loan_repayments_received = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_loans = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_nonfederal_transfers = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_offset_to_operating_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_operating_expenditures = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_receipts = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_total_refunds = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_transfers_from_aff_other_party_cmttees = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_transfers_from_authorized = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_transfers_from_nonfederal_h3 = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_transfers_to_affiliated = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    cycle_transfers_to_other_authorized_committees = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)

class ScheduleA(BaseModel):
    form_type = models.CharField(max_length=255, null=True, blank=True)
    filer_committee_id_number = models.CharField(max_length=255, null=True, blank=True)
    filing_id = models.IntegerField(null=True, blank=True)
    transaction_id = models.CharField(max_length=255, null=True, blank=True)
    back_reference_tran_id_number = models.CharField(max_length=255, null=True, blank=True)
    back_reference_sched_name = models.CharField(max_length=255, null=True, blank=True)
    entity_type = models.CharField(max_length=255, null=True, blank=True)
    contributor_organization_name = models.CharField(max_length=255, null=True, blank=True)
    contributor_last_name = models.CharField(max_length=255, null=True, blank=True)
    contributor_first_name = models.CharField(max_length=255, null=True, blank=True)
    contributor_middle_name = models.CharField(max_length=255, null=True, blank=True)
    contributor_prefix = models.CharField(max_length=255, null=True, blank=True)
    contributor_suffix = models.CharField(max_length=255, null=True, blank=True)
    contributor_street_1 = models.CharField(max_length=255, null=True, blank=True)
    contributor_street_2 = models.CharField(max_length=255, null=True, blank=True)
    contributor_city = models.CharField(max_length=255, null=True, blank=True)
    contributor_state = models.CharField(max_length=30, null=True, blank=True)
    contributor_zip = models.CharField(max_length=10, null=True, blank=True)
    election_code = models.CharField(max_length=255, null=True, blank=True)
    election_other_description = models.CharField(max_length=255, null=True, blank=True)
    contribution_date = models.CharField(max_length=255, null=True, blank=True)
    contribution_amount = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    contribution_aggregate = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    contribution_purpose_descrip = models.CharField(max_length=255, null=True, blank=True)
    contributor_employer = models.CharField(max_length=255, null=True, blank=True)
    contributor_occupation = models.CharField(max_length=255, null=True, blank=True)
    donor_committee_fec_id = models.CharField(max_length=255, null=True, blank=True)
    donor_committee_name = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_fec_id = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_last_name = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_first_name = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_middle_name = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_prefix = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_suffix = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_office = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_state = models.CharField(max_length=255, null=True, blank=True)
    donor_candidate_district = models.CharField(max_length=255, null=True, blank=True)
    conduit_name = models.CharField(max_length=255, null=True, blank=True)
    conduit_street1 = models.CharField(max_length=255, null=True, blank=True)
    conduit_street2 = models.CharField(max_length=255, null=True, blank=True)
    conduit_city = models.CharField(max_length=255, null=True, blank=True)
    conduit_state = models.CharField(max_length=255, null=True, blank=True)
    conduit_zip = models.CharField(max_length=255, null=True, blank=True)
    memo_code = models.CharField(max_length=255, null=True, blank=True)
    memo_text_description = models.CharField(max_length=255, null=True, blank=True)
    reference_code = models.CharField(max_length=255, null=True, blank=True)

class ScheduleB(BaseModel):
    form_type = models.CharField(max_length=255, null=True, blank=True)
    filer_committee_id_number = models.CharField(max_length=255, null=True, blank=True)
    filing_id = models.IntegerField(null=True, blank=True)
    transaction_id = models.CharField(max_length=255, null=True, blank=True)
    back_reference_tran_id_number = models.CharField(max_length=255, null=True, blank=True)
    back_reference_sched_name = models.CharField(max_length=255, null=True, blank=True)
    entity_type = models.CharField(max_length=255, null=True, blank=True)
    payee_organization_name = models.CharField(max_length=255, null=True, blank=True)
    payee_last_name = models.CharField(max_length=255, null=True, blank=True)
    payee_first_name = models.CharField(max_length=255, null=True, blank=True)
    payee_middle_name = models.CharField(max_length=255, null=True, blank=True)
    payee_prefix = models.CharField(max_length=255, null=True, blank=True)
    payee_suffix = models.CharField(max_length=255, null=True, blank=True)
    payee_street_1 = models.CharField(max_length=255, null=True, blank=True)
    payee_street_2 = models.CharField(max_length=255, null=True, blank=True)
    payee_city = models.CharField(max_length=255, null=True, blank=True)
    payee_state = models.CharField(max_length=30, null=True, blank=True)
    payee_zip = models.CharField(max_length=10, null=True, blank=True)
    election_code = models.CharField(max_length=255, null=True, blank=True)
    election_other_description = models.CharField(max_length=255, null=True, blank=True)
    expenditure_date = models.CharField(max_length=255, null=True, blank=True)
    expenditure_amount = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    semi_annual_refunded_bundled_amt = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    expenditure_purpose_descrip = models.CharField(max_length=255, null=True, blank=True)
    category_code = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_committee_fec_id = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_committee_name = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_fec_id = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_last_name = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_first_name = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_middle_name = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_prefix = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_suffix = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_office = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_state = models.CharField(max_length=255, null=True, blank=True)
    beneficiary_candidate_district = models.CharField(max_length=255, null=True, blank=True)
    conduit_name = models.CharField(max_length=255, null=True, blank=True)
    conduit_street_1 = models.CharField(max_length=255, null=True, blank=True)
    conduit_street_2 = models.CharField(max_length=255, null=True, blank=True)
    conduit_city = models.CharField(max_length=255, null=True, blank=True)
    conduit_state = models.CharField(max_length=255, null=True, blank=True)
    conduit_zip = models.CharField(max_length=255, null=True, blank=True)
    memo_code = models.CharField(max_length=255, null=True, blank=True)
    memo_text_description = models.CharField(max_length=255, null=True, blank=True)
    reference_to_si_or_sl_system_code_that_identifies_the_account = models.CharField(max_length=255, null=True, blank=True)

class ScheduleE(BaseModel):
    form_type = models.CharField(max_length=255, null=True, blank=True)
    filer_committee_id_number = models.CharField(max_length=255, null=True, blank=True)
    filing_id = models.IntegerField(null=True, blank=True)
    transaction_id = models.CharField(max_length=255, null=True, blank=True)
    back_reference_tran_id_number = models.CharField(max_length=255, null=True, blank=True)
    back_reference_sched_name = models.CharField(max_length=255, null=True, blank=True)
    entity_type = models.CharField(max_length=255, null=True, blank=True)
    payee_organization_name = models.CharField(max_length=255, null=True, blank=True)
    payee_last_name = models.CharField(max_length=255, null=True, blank=True)
    payee_first_name = models.CharField(max_length=255, null=True, blank=True)
    payee_middle_name = models.CharField(max_length=255, null=True, blank=True)
    payee_prefix = models.CharField(max_length=255, null=True, blank=True)
    payee_suffix = models.CharField(max_length=255, null=True, blank=True)
    payee_street_1 = models.CharField(max_length=255, null=True, blank=True)
    payee_street_2 = models.CharField(max_length=255, null=True, blank=True)
    payee_city = models.CharField(max_length=255, null=True, blank=True)
    payee_state = models.CharField(max_length=30, null=True, blank=True)
    payee_zip = models.CharField(max_length=10, null=True, blank=True)
    election_code = models.CharField(max_length=255, null=True, blank=True)
    election_other_description = models.CharField(max_length=255, null=True, blank=True)
    dissemination_date = models.CharField(max_length=255, null=True, blank=True)
    expenditure_amount = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    expenditure_date = models.CharField(max_length=255, null=True, blank=True)
    calendar_y_t_d_per_election_office = models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True)
    expenditure_purpose_descrip = models.CharField(max_length=255, null=True, blank=True)
    category_code = models.CharField(max_length=255, null=True, blank=True)
    payee_cmtte_fec_id_number = models.CharField(max_length=255, null=True, blank=True)
    support_oppose_code = models.CharField(max_length=255, null=True, blank=True)
    candidate_id_number = models.CharField(max_length=255, null=True, blank=True)
    candidate_last_name = models.CharField(max_length=255, null=True, blank=True)
    candidate_first_name = models.CharField(max_length=255, null=True, blank=True)
    candidate_middle_name = models.CharField(max_length=255, null=True, blank=True)
    candidate_prefix = models.CharField(max_length=255, null=True, blank=True)
    candidate_suffix = models.CharField(max_length=255, null=True, blank=True)
    candidate_office = models.CharField(max_length=255, null=True, blank=True)
    candidate_district = models.CharField(max_length=255, null=True, blank=True)
    candidate_state = models.CharField(max_length=255, null=True, blank=True)
    completing_last_name = models.CharField(max_length=255, null=True, blank=True)
    completing_first_name = models.CharField(max_length=255, null=True, blank=True)
    completing_middle_name = models.CharField(max_length=255, null=True, blank=True)
    completing_prefix = models.CharField(max_length=255, null=True, blank=True)
    completing_suffix = models.CharField(max_length=255, null=True, blank=True)
    date_signed = models.CharField(max_length=255, null=True, blank=True)
    memo_code = models.CharField(max_length=255, null=True, blank=True)
    memo_text_description = models.CharField(max_length=255, null=True, blank=True)