# Generated by Django 2.0.1 on 2018-02-16 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0002_auto_20180216_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fec_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('committee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_1', models.CharField(blank=True, max_length=255, null=True)),
                ('street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('treasurer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_type', models.CharField(blank=True, max_length=1, null=True)),
                ('committee_designation', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
