# Generated by Django 2.0.1 on 2018-02-16 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0003_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('form_type', models.CharField(blank=True, max_length=255, null=True)),
                ('filer_committee_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_id', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('back_reference_tran_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('back_reference_sched_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_first_nam', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_street_1', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_city', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_state', models.CharField(blank=True, max_length=30, null=True)),
                ('contributor_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('election_code', models.CharField(blank=True, max_length=255, null=True)),
                ('election_other_description', models.CharField(blank=True, max_length=255, null=True)),
                ('contribution_date', models.CharField(blank=True, max_length=255, null=True)),
                ('contribution_amount', models.IntegerField(blank=True, null=True)),
                ('contribution_aggregate', models.IntegerField(blank=True, null=True)),
                ('contribution_purpose_descrip', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_committee_fec_id', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_committee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_fec_id', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_office', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_state', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_candidate_district', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_street1', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_street2', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_city', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_state', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('memo_code', models.CharField(blank=True, max_length=255, null=True)),
                ('memo_text_description', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
