# Generated by Django 2.0.1 on 2018-02-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0005_auto_20180216_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulea',
            name='contribution_aggregate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='schedulea',
            name='contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
