# Generated by Django 2.0.1 on 2018-02-16 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0006_auto_20180216_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('form_type', models.CharField(blank=True, max_length=255, null=True)),
                ('filer_committee_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_id', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('back_reference_tran_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('back_reference_sched_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_street_1', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_city', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_state', models.CharField(blank=True, max_length=30, null=True)),
                ('payee_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('election_code', models.CharField(blank=True, max_length=255, null=True)),
                ('election_other_description', models.CharField(blank=True, max_length=255, null=True)),
                ('expenditure_date', models.CharField(blank=True, max_length=255, null=True)),
                ('expenditure_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('semi_annual_refunded_bundled_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expenditure_purpose_descrip', models.CharField(blank=True, max_length=255, null=True)),
                ('category_code', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_committee_fec_id', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_committee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_fec_id', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_office', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_state', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_candidate_district', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_street_1', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_city', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_state', models.CharField(blank=True, max_length=255, null=True)),
                ('conduit_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('memo_code', models.CharField(blank=True, max_length=255, null=True)),
                ('memo_text_description', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_to_si_or_sl_system_code_that_identifies_the_account', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
