# Generated by Django 2.0.1 on 2018-02-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0008_schedulee'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo')], default='ACTIVE', max_length=50),
        ),
    ]
