# Generated by Django 2.0.1 on 2018-02-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0009_auto_20180222_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='amends_filing',
            field=models.IntegerField(help_text='the filing id of the filing this filing amends', null=True),
        ),
    ]
