# Generated by Django 2.0.1 on 2018-02-23 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0010_filing_amends_filing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulea',
            name='back_reference_sched_name',
        ),
        migrations.RemoveField(
            model_name='schedulea',
            name='back_reference_tran_id_number',
        ),
        migrations.RemoveField(
            model_name='schedulea',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='schedulea',
            name='filer_committee_id_number',
        ),
        migrations.RemoveField(
            model_name='schedulea',
            name='filing_id',
        ),
        migrations.RemoveField(
            model_name='schedulea',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='schedulea',
            name='status',
        ),
        migrations.RemoveField(
            model_name='schedulea',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='back_reference_sched_name',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='back_reference_tran_id_number',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='filer_committee_id_number',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='filing_id',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scheduleb',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='back_reference_sched_name',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='back_reference_tran_id_number',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='filer_committee_id_number',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='filing_id',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='schedulee',
            name='transaction_id',
        ),
    ]
