# Generated by Django 2.0.1 on 2018-02-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0011_auto_20180223_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulea',
            name='back_reference_sched_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='back_reference_tran_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='entity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='filer_committee_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='filer_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='filing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='form_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='back_reference_sched_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='back_reference_tran_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='entity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='filer_committee_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='filer_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='filing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='form_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='back_reference_sched_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='back_reference_tran_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='entity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='filer_committee_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='filer_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='filing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='form_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
