# Generated by Django 2.0.1 on 2018-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0012_auto_20180223_0047'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['fec_id'], name='fec_committ_fec_id_8997b5_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['committee_name'], name='fec_committ_committ_964f98_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['filer_id'], name='fec_filing_filer_i_58b8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['filing_id'], name='fec_filing_filing__04f206_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['committee_name'], name='fec_filing_committ_9fd6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filing_id'], name='fec_schedul_filing__c2723a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filer_id'], name='fec_schedul_filer_i_225952_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=models.Index(fields=['filing_id'], name='fec_schedul_filing__7986b7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=models.Index(fields=['filer_id'], name='fec_schedul_filer_i_68d328_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=models.Index(fields=['filing_id'], name='fec_schedul_filing__7150bd_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=models.Index(fields=['filer_id'], name='fec_schedul_filer_i_3b86a7_idx'),
        ),
    ]
