# Generated by Django 2.0.1 on 2018-03-07 20:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0014_auto_20180302_1937'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_filing__c2723a_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_filer_i_225952_idx',
        ),
        migrations.AddField(
            model_name='schedulea',
            name='name_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='schedulea',
            name='occupation_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='fec_schedul_name_se_4bbed2_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['occupation_search'], name='fec_schedul_occupat_7fd4d2_gin'),
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER contribution_name_update_trigger
            BEFORE INSERT OR UPDATE OF contributor_organization_name, contributor_first_name, contributor_middle_name, contributor_last_name, name_search
            ON fec_schedulea
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              name_search, 'pg_catalog.english', contributor_organization_name, contributor_first_name, contributor_middle_name, contributor_last_name);

            UPDATE fec_schedulea SET name_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS contribution_name_update_trigger
            ON fec_schedulea;
            '''),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER contribution_occupation_update_trigger
            BEFORE INSERT OR UPDATE OF contributor_occupation, contributor_employer, occupation_search
            ON fec_schedulea
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              occupation_search, 'pg_catalog.english', contributor_occupation, contributor_employer);

            UPDATE fec_schedulea SET occupation_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS contribution_occupation_update_trigger
            ON fec_schedulea;
            '''),
    ]
