# Generated by Django 2.0.1 on 2018-03-12 17:07

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0015_auto_20180307_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='name_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filing_id'], name='fec_schedul_filing__c2723a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filer_id'], name='fec_schedul_filer_i_225952_idx'),
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER committee_name_update_trigger
            BEFORE INSERT OR UPDATE OF committee_name, fec_id, name_search
            ON fec_committee
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              name_search, 'pg_catalog.english', fec_id, committee_name);

            UPDATE fec_committee SET name_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS committee_name_update_trigger
            ON fec_committee;
            '''),
    ]
