# Generated by Django 2.0.1 on 2018-03-12 18:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0016_auto_20180312_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleb',
            name='name_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleb',
            name='purpose_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='fec_committ_name_se_dfbacd_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='fec_schedul_name_se_68d076_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_search'], name='fec_schedul_purpose_11a837_gin'),
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER expenditure_name_update_trigger
            BEFORE INSERT OR UPDATE OF payee_organization_name, payee_first_name, payee_middle_name, payee_last_name, name_search
            ON fec_scheduleb
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              name_search, 'pg_catalog.english', payee_organization_name, payee_first_name, payee_middle_name, payee_last_name);

            UPDATE fec_scheduleb SET name_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS expenditure_name_update_trigger
            ON fec_scheduleb;
            '''),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER expenditure_purpose_update_trigger
            BEFORE INSERT OR UPDATE OF expenditure_purpose_descrip, purpose_search
            ON fec_scheduleb
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              purpose_search, 'pg_catalog.english', expenditure_purpose_descrip);

            UPDATE fec_scheduleb SET purpose_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS expenditure_purpose_update_trigger
            ON fec_scheduleb;
            '''),
    ]
