# Generated by Django 2.0.1 on 2018-03-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0017_auto_20180312_1807'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_filer_i_225952_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='fec_schedul_filer_i_68d328_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='fec_schedul_filer_i_3b86a7_idx',
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filer_committee_id_number'], name='fec_schedul_filer_c_53e206_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=models.Index(fields=['filer_committee_id_number'], name='fec_schedul_filer_c_28c2de_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=models.Index(fields=['filer_committee_id_number'], name='fec_schedul_filer_c_4df0ea_idx'),
        ),
    ]
