# Generated by Django 2.0.1 on 2018-03-12 18:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0018_auto_20180312_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulee',
            name='candidate_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='name_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='schedulee',
            name='purpose_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='fec_schedul_name_se_1473cd_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_search'], name='fec_schedul_purpose_425f2a_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['candidate_search'], name='fec_schedul_candida_6538b6_gin'),
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER ie_name_update_trigger
            BEFORE INSERT OR UPDATE OF payee_organization_name,payee_first_name, payee_middle_name, payee_last_name, name_search
            ON fec_schedulee
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              name_search, 'pg_catalog.english', payee_organization_name, payee_first_name, payee_middle_name, payee_last_name);

            UPDATE fec_schedulee SET name_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS ie_name_update_trigger
            ON fec_schedulee;
            '''),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER ie_purpose_update_trigger
            BEFORE INSERT OR UPDATE OF expenditure_purpose_descrip, purpose_search
            ON fec_schedulee
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              purpose_search, 'pg_catalog.english', expenditure_purpose_descrip);

            UPDATE fec_schedulee SET purpose_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS ie_purpose_update_trigger
            ON fec_schedulee;
            '''),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER ie_candidate_update_trigger
            BEFORE INSERT OR UPDATE OF candidate_first_name, candidate_middle_name, candidate_last_name, candidate_search
            ON fec_schedulee
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              candidate_search, 'pg_catalog.english', candidate_first_name, candidate_middle_name, candidate_last_name);

            UPDATE fec_schedulee SET candidate_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS ie_candidate_update_trigger
            ON fec_schedulee;
            '''),
    ]
