# Generated by Django 2.0.1 on 2018-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0019_auto_20180312_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='election_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
