# Generated by Django 2.0.1 on 2018-03-14 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0020_filing_election_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nyt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nyt_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('nyt_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('nyt_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
