# Generated by Django 2.0.1 on 2018-03-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0022_schedulea_donor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['contribution_amount'], name='fec_schedul_contrib_5de3c3_idx'),
        ),
    ]
