# Generated by Django 2.0.1 on 2018-07-21 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0026_donor_contribution_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulea',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle_2018.Donor'),
        ),
    ]
