# Generated by Django 2.0.1 on 2018-07-24 18:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0028_schedulea_old_donor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulea',
            name='address_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address_search'], name='fec_schedul_address_804b9a_gin'),
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER contribution_address_update_trigger
            BEFORE INSERT OR UPDATE OF contributor_street_1, contributor_street_2, contributor_city, contributor_zip, address_search
            ON fec_schedulea
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              address_search, 'pg_catalog.english', contributor_street_1, contributor_street_2, contributor_city, contributor_zip);

            UPDATE fec_schedulea SET address_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS contribution_address_update_trigger
            ON fec_schedulea;
            '''),
    ]
