# Generated by Django 2.0.1 on 2018-08-13 16:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0030_filing_computed_ie_total_for_f24'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleb',
            name='address_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address_search'], name='fec_schedul_address_5ea139_gin'),
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER expenditure_address_update_trigger
            BEFORE INSERT OR UPDATE OF payee_street_1, payee_street_2, payee_city, payee_zip, address_search
            ON fec_scheduleb
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              address_search, 'pg_catalog.english', payee_street_1, payee_street_2, payee_city, payee_zip);

            UPDATE fec_scheduleb SET address_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS expenditure_address_update_trigger
            ON fec_scheduleb;
            '''),
    ]
