# Generated by Django 2.0.1 on 2018-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0031_auto_20180813_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulee',
            name='nyt_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
