# Generated by Django 2.1.2 on 2018-10-05 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0032_schedulee_nyt_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('district_number', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=23, null=True)),
                ('fec_candidate_id', models.CharField(blank=True, max_length=9, null=True)),
                ('fec_committee_id', models.CharField(blank=True, max_length=9, null=True)),
                ('party', models.CharField(blank=True, max_length=1, null=True)),
                ('office', models.CharField(blank=True, max_length=1, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='filing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo'), ('PROCESSING', 'processing'), ('FAILED', 'failed'), ('WRONG_CYCLE', 'wrong cycle')], default='PROCESSING', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedulea',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo'), ('PROCESSING', 'processing'), ('FAILED', 'failed'), ('WRONG_CYCLE', 'wrong cycle')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleb',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo'), ('PROCESSING', 'processing'), ('FAILED', 'failed'), ('WRONG_CYCLE', 'wrong cycle')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedulee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('SUPERSEDED', 'superseded by amendment'), ('COVERED', 'covered by periodic'), ('MEMO', 'memo'), ('PROCESSING', 'processing'), ('FAILED', 'failed'), ('WRONG_CYCLE', 'wrong cycle')], default='ACTIVE', max_length=50),
        ),
    ]
