# Generated by Django 2.1.2 on 2018-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0033_auto_20181005_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='incumbent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
