# Generated by Django 2.1.2 on 2019-01-08 19:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0035_inauguralcontrib'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='committee',
            name='fec_committ_fec_id_8997b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='committee',
            name='fec_committ_committ_964f98_idx',
        ),
        migrations.RemoveIndex(
            model_name='committee',
            name='fec_committ_name_se_dfbacd_gin',
        ),
        migrations.RemoveIndex(
            model_name='filing',
            name='fec_filing_filer_i_58b8c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='filing',
            name='fec_filing_filing__04f206_idx',
        ),
        migrations.RemoveIndex(
            model_name='filing',
            name='fec_filing_committ_9fd6d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_name_se_4bbed2_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_occupat_7fd4d2_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_filing__c2723a_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_filer_c_53e206_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_contrib_5de3c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='fec_schedul_address_804b9a_gin',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='fec_schedul_filing__7986b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='fec_schedul_name_se_68d076_gin',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='fec_schedul_purpose_11a837_gin',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='fec_schedul_filer_c_28c2de_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='fec_schedul_address_5ea139_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='fec_schedul_filing__7150bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='fec_schedul_filer_c_4df0ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='fec_schedul_name_se_1473cd_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='fec_schedul_purpose_425f2a_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='fec_schedul_candida_6538b6_gin',
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['fec_id'], name='cycle_2018__fec_id_f4fdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['committee_name'], name='cycle_2018__committ_c028f2_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2018__name_se_7a2d50_gin'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['filer_id'], name='cycle_2018__filer_i_254d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['filing_id'], name='cycle_2018__filing__c7b61a_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['committee_name'], name='cycle_2018__committ_43226b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filing_id'], name='cycle_2018__filing__750e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filer_committee_id_number'], name='cycle_2018__filer_c_5e3bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2018__name_se_05d231_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['contribution_amount'], name='cycle_2018__contrib_d1e32a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['occupation_search'], name='cycle_2018__occupat_d47d12_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address_search'], name='cycle_2018__address_ab4e5a_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=models.Index(fields=['filing_id'], name='cycle_2018__filing__7805a2_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=models.Index(fields=['filer_committee_id_number'], name='cycle_2018__filer_c_6b2904_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2018__name_se_0a35cc_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_search'], name='cycle_2018__purpose_17995a_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address_search'], name='cycle_2018__address_f469ae_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=models.Index(fields=['filing_id'], name='cycle_2018__filing__91be16_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=models.Index(fields=['filer_committee_id_number'], name='cycle_2018__filer_c_b78a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2018__name_se_118184_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_search'], name='cycle_2018__purpose_1d14f3_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['candidate_search'], name='cycle_2018__candida_175b6a_gin'),
        ),
    ]
