# Generated by Django 2.1.2 on 2019-01-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0036_auto_20190108_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulea',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.Donor'),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
