# Generated by Django 2.1.2 on 2019-01-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2018', '0037_auto_20190115_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulea',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_2018', to='donor.Donor'),
        ),
    ]
