# Generated by Django 2.1.5 on 2019-01-23 19:49

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2020', '0001_squashed_0038_auto_20190115_1828'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='committee',
            name='cycle_2020__fec_id_f4fdd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='committee',
            name='cycle_2020__committ_c028f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='committee',
            name='cycle_2020__name_se_7a2d50_gin',
        ),
        migrations.RemoveIndex(
            model_name='filing',
            name='cycle_2020__filer_i_254d8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='filing',
            name='cycle_2020__filing__c7b61a_idx',
        ),
        migrations.RemoveIndex(
            model_name='filing',
            name='cycle_2020__committ_43226b_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='cycle_2020_address_804b9a_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='cycle_2020__filing__750e4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='cycle_2020__filer_c_5e3bbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='cycle_2020__name_se_05d231_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='cycle_2020__contrib_d1e32a_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='cycle_2020__occupat_d47d12_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulea',
            name='cycle_2020__address_ab4e5a_gin',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='cycle_2020__filing__7805a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='cycle_2020__filer_c_6b2904_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='cycle_2020__name_se_0a35cc_gin',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='cycle_2020__purpose_17995a_gin',
        ),
        migrations.RemoveIndex(
            model_name='scheduleb',
            name='cycle_2020__address_f469ae_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='cycle_2020__filing__91be16_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='cycle_2020__filer_c_b78a8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='cycle_2020__name_se_118184_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='cycle_2020__purpose_1d14f3_gin',
        ),
        migrations.RemoveIndex(
            model_name='schedulee',
            name='cycle_2020__candida_175b6a_gin',
        ),
        migrations.AlterField(
            model_name='filing',
            name='filing_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['fec_id'], name='cycle_2020__fec_id_244f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['committee_name'], name='cycle_2020__committ_319402_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2020__name_se_0499a0_gin'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['filer_id'], name='cycle_2020__filer_i_669360_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['filing_id'], name='cycle_2020__filing__0f4177_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['committee_name'], name='cycle_2020__committ_a8729f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filing_id'], name='cycle_2020__filing__4d2e86_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['filer_committee_id_number'], name='cycle_2020__filer_c_e2edfc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2020__name_se_866f1e_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=models.Index(fields=['contribution_amount'], name='cycle_2020__contrib_3874aa_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['occupation_search'], name='cycle_2020__occupat_7e8387_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address_search'], name='cycle_2020__address_fef428_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=models.Index(fields=['filing_id'], name='cycle_2020__filing__cf0841_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=models.Index(fields=['filer_committee_id_number'], name='cycle_2020__filer_c_b11732_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2020__name_se_9feb48_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_search'], name='cycle_2020__purpose_b8ba26_gin'),
        ),
        migrations.AddIndex(
            model_name='scheduleb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address_search'], name='cycle_2020__address_17a51e_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=models.Index(fields=['filing_id'], name='cycle_2020__filing__b1d78a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=models.Index(fields=['filer_committee_id_number'], name='cycle_2020__filer_c_c66501_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='cycle_2020__name_se_bbc60d_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_search'], name='cycle_2020__purpose_3469db_gin'),
        ),
        migrations.AddIndex(
            model_name='schedulee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['candidate_search'], name='cycle_2020__candida_55a787_gin'),
        ),
    ]
