# Generated by Django 2.0.1 on 2018-03-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0021_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulea',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fec.Donor'),
        ),
    ]
